### ISSUE TITLE
Wrong water level on Islands

### ISSUE THREAD

**Issue by Emeraldclover** [jetelain/ArmaRealMap#52]
when generating a Island Terrain the water level of the ocean around it is less than 5 centimeters

**Comment by jetelain** [comment]
Islands are not yet supported, elevation of ocean is zero according to source that is used by default (SRTM) due to the way the information have been collected. 

I've [prepared support for "SRTM15+"](https://github.com/jetelain/mapkit/commit/26ad0866f479db254c15ff387e358f87dd2c5396) on https://dem.pmad.net/SRTM15Plus/, that can be combined with OpenStreetMap data to get correct ocean depth.

I plan to work on it in septembre.

**Comment by Eagle-Studios** [comment]
This is still an issue: Island of Ushant used.. and the entire around around the island (which on the map is the darker ocean colour) is set to be incorrect terrain height. 
https://i.gyazo.com/33a462a6d6fb417ce695b4eed879bfb6.png
https://i.gyazo.com/d58eba9af785622570e444638845a5c5.jpg

also the exact same issue for islands not included in the map, but included in the outer terrain area..
https://i.gyazo.com/9c461905cc06763751d7426e8b203155.png
(taken at the terrain edge) https://i.gyazo.com/3ff4aa25466a6f30e31fd3104c78b00f.jpg
