### ISSUE TITLE
What is the differense between main and general-purpose branch

### ISSUE THREAD

**Issue by wwwronin** [jetelain/ArmaRealMap#8]
What is the differense between main and general-purpose branch?

**Comment by jetelain** [comment]
Hi, 
the general-purpose is a complete rewrite of the generator system to be able to target any game engine in the future. 
It will also includes a GUI tool to configure map and assets (instead of the website)
See #7 for more information.

**Comment by wwwronin** [comment]
Hi , 
That sounds amazing. I have anther questions here. The program download SC sattlite image is very slowly, do you consider that we can import a geotiff sattlite imagery or geotiff elevation files?  Does 'sat-raw.png' just a combined imagery or has any coordinate(like UTM or WGS-84)?

**Comment by jetelain** [comment]
Hi,
The satellite image is slow due to the projection library I used, it's not a downloading issue. I've made some optimizations (in the library) : it's 10 to 15x faster.

`sat-raw` is a UTM projected satellite image matching map coordinates. Like all other data, it's projected using UTM zone of south-west point. In general-purpose it will be possible to project using UTM zone of map center point, or some custom projection to reduce deformation at edges.

For elevation, it's planned to allow use of other sources.  I've already added AWD30 and SRTM+ to be able to process any place in the world. GeoTIFF is already supported, but only for "unprojected WGS-84" data (like AWD30).

For satellite/aerial imagery, it might be also possible.
